spring:
  datasource:
    # \u914D\u7F6E\u6570\u636E\u6E90\u7C7B\u578B
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin



