  spring:
    datasource:
      # 配置数据源类型
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT&characterEncoding=utf-8&useSSL=false
      username: root
      password: admin

  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:/mapper/*.xml
    # 设置mybatis-plus全局配置
    global-config:
      db-config:
        # 设置表名统一前缀
        table-prefix: mp_
        # 配置主键生成策略
        id-type: auto
    # 配置类型别名所在的包
    type-aliases-package: com.chenjy.mp_demo.pojo
    # 扫描通用枚举的包
    type-enums-package: com.chenjy.mp_demo.enums

