spring:
  # 配置数据源信息
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为master
      primary: master
      # 严格匹配数据源,默认false.true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: true
      datasource:
        master: # 可随意取名
          url: jdbc:mysql://localhost:3306/mp_demo1?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: admin
        slave_1: # 可随意取名
          url: jdbc:mysql://localhost:3306/mp_demo2?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: admin
        # druid配置，可直接使用默认值
        druid:
          #初始化时建立物理连接的个数
          initialSize: 1
          #池中最大连接数
          maxActive: 20
          #最小空闲连接
          minIdle: 1
          #获取连接时最大等待时间，单位毫秒
          maxWait: 60000

server:
  port: 8089
